require File.expand_path("../../lib/buzzoink",  __FILE__)
require 'vcr'
require 'fabrication'

VCR.configure do |c|
  c.cassette_library_dir = File.expand_path("../../spec/factories/vcr",  __FILE__)
  c.hook_into 'excon'
  # c.default_cassette_options = {:record => :all}
  c.configure_rspec_metadata!
end

Fabrication.configure do |config|
  fabricator_dir = File.expand_path("../../spec/factories",  __FILE__)
end
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  # config.filter_run :focus
end

def job_hash
{
  "Instances"=> {
    "InstanceGroups"=>[
      { "CreationDateTime"=>"2012-02-09T18:45:39Z", 
        "InstanceRunningCount"=>"1", 
        "StartDateTime"=>"2012-02-09T18:49:06Z", 
        "ReadyDateTime"=>"2012-02-09T18:50:21Z", 
        "State"=>"RUNNING", 
        "InstanceRequestCount"=>"1", 
        "InstanceType"=>"m1.small", 
        "Market"=>"ON_DEMAND", 
        "LastStateChangeReason"=>nil, 
        "InstanceRole"=>"MASTER", 
        "InstanceGroupId"=>"ig-2ZOB6FYVH6U3P", 
        "Name"=>"Master group"
      }, 
      {
        "CreationDateTime"=>"2012-02-09T18:45:39Z", 
        "InstanceRunningCount"=>"1", 
        "StartDateTime"=>"2012-02-09T18:50:22Z", 
        "ReadyDateTime"=>"2012-02-09T18:50:22Z", 
        "State"=>"RUNNING", 
        "InstanceRequestCount"=>"1", 
        "InstanceType"=>"c1.medium", 
        "Market"=>"ON_DEMAND", 
        "LastStateChangeReason"=>nil, 
        "InstanceRole"=>"CORE", 
        "InstanceGroupId"=>"ig-31TJZJDKAUPZG", 
        "Name"=>"Compute group"
      }
    ], 
    "Placement"=> {
      "AvailabilityZone"=>"us-east-1d"
    }, 
    "MasterInstanceType"=>"m1.small", 
    "KeepJobFlowAliveWhenNoSteps"=>"true", 
    "SlaveInstanceType"=>"c1.medium", 
    "MasterInstanceId"=>"i-911e78f4", 
    "NormalizedInstanceHours"=>"3", 
    "HadoopVersion"=>"0.20.205", 
    "MasterPublicDnsName"=>"ec2-50-16-148-218.compute-1.amazonaws.com", 
    "InstanceCount"=>"2", 
    "TerminationProtected"=>"false"
  }, 
  "ExecutionStatusDetail"=> {
    "CreationDateTime"=>"2012-02-09T18:45:39Z", 
    "LastStateChangeReason"=>"Waiting for steps to run", 
    "StartDateTime"=>"2012-02-09T18:50:22Z", 
    "ReadyDateTime"=>"2012-02-09T18:50:22Z", 
    "State"=>"WAITING"
  }, 
  "BootstrapActions"=> {
    "ScriptBootstrapActionConfig"=> {
      "Args"=>[]
    }
  }, 
  "Steps"=>[], 
  "AmiVersion"=>"2.0", 
  "Name"=>"Managed Buzzoink process : Main EMR process type => hive", 
  "JobFlowId"=>"j-8Z5WJTNRBILW"
}
end

